'use server';
/**
 * @fileOverview Provides AI-powered inventory suggestions based on sales data.
 *
 * - optimizedInventorySuggestions - A function that generates optimal reorder quantities and identifies best-selling items.
 * - OptimizedInventorySuggestionsInput - The input type for the optimizedInventorySuggestions function.
 * - OptimizedInventorySuggestionsOutput - The return type for the optimizedInventorySuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Input Schemas
const ProductSchema = z.object({
  id: z.number().describe('Unique identifier for the product.'),
  nombre: z.string().describe('Name of the product.'),
  categoria: z.string().describe('Category of the product (e.g., "lubricante", "repuesto", "servicio").'),
  stock: z.number().describe('Current stock level of the product.'),
  costo: z.number().describe('Cost of the product.'),
  precio: z.number().describe('Selling price of the product.'),
  unidad: z.string().describe('Unit of measurement for the product (e.g., "litro", "pieza", "servicio").'),
});

const SaleItemSchema = z.object({
  id: z.number().describe('ID of the product sold.'),
  nombre: z.string().describe('Name of the product sold.'),
  cantidad: z.number().describe('Quantity of the product sold.'),
  precio: z.number().describe('Price of the product at the time of sale.'),
});

const SaleSchema = z.object({
  id: z.number().describe('Unique identifier for the sale transaction.'),
  fecha: z.string().describe('ISO formatted date string of the sale.'),
  items: z.array(SaleItemSchema).describe('List of items included in the sale.'),
});

const OptimizedInventorySuggestionsInputSchema = z.object({
  products: z.array(ProductSchema).describe('The current list of all products with their inventory details.'),
  sales: z.array(SaleSchema).describe('Historical sales data, including items sold and sale dates.'),
});
export type OptimizedInventorySuggestionsInput = z.infer<typeof OptimizedInventorySuggestionsInputSchema>;

// Output Schemas
const ReorderSuggestionSchema = z.object({
  productId: z.number().describe('The ID of the product.'),
  productName: z.string().describe('The name of the product.'),
  currentStock: z.number().describe('The current stock level of the product.'),
  suggestedReorderQuantity: z.number().describe('The suggested quantity to reorder for this product. Should be 0 if no reorder is needed, e.g., for services or sufficient stock.'),
  reason: z.string().describe('The reasoning for the reorder suggestion, based on sales trends, current stock, and product type.'),
});

const BestSellingItemSchema = z.object({
  productId: z.number().describe('The ID of the best-selling product.'),
  productName: z.string().describe('The name of the best-selling product.'),
  totalQuantitySold: z.number().describe('The total quantity of this product sold across all historical sales records.'),
  totalRevenue: z.number().describe('The total revenue generated by this product across all historical sales records.'),
});

const OptimizedInventorySuggestionsOutputSchema = z.object({
  reorderSuggestions: z.array(ReorderSuggestionSchema).describe('A list of products with their suggested reorder quantities.'),
  bestSellingItems: z.array(BestSellingItemSchema).describe('A list of best-selling products, ordered by total quantity sold in descending order.'),
});
export type OptimizedInventorySuggestionsOutput = z.infer<typeof OptimizedInventorySuggestionsOutputSchema>;

// Internal schema for the prompt after aggregation
const AggregatedProductDataSchema = z.object({
  id: z.number(),
  nombre: z.string(),
  categoria: z.string(),
  stock: z.number(),
  costo: z.number(),
  precio: z.number(),
  unidad: z.string(),
  totalQuantitySold: z.number().describe('Total quantity of this product sold historically.'),
  totalRevenue: z.number().describe('Total revenue generated by this product historically.'),
});

const PromptInputSchema = z.object({
  productsWithSalesJson: z.string().describe('JSON stringified list of products including their current stock and aggregated historical sales data.'),
});

const inventoryPrompt = ai.definePrompt({
  name: 'optimizedInventoryPrompt',
  input: { schema: PromptInputSchema },
  output: { schema: OptimizedInventorySuggestionsOutputSchema },
  prompt: `You are an expert inventory manager. Your task is to analyze the provided product data, which includes current stock levels and historical aggregated sales information, to offer optimized reorder suggestions and identify best-selling items.

Here is the aggregated product data:
{{{productsWithSalesJson}}}

Based on this data, please provide:
1.  **Reorder Suggestions**: For each product, assess its current stock relative to its historical sales volume. Suggest a 'suggestedReorderQuantity'.
    - For products with "categoria: servicio" (services), the 'suggestedReorderQuantity' should always be 0.
    - If 'currentStock' is 999 (indicating unlimited stock), the 'suggestedReorderQuantity' should also be 0.
    - For other products, if 'currentStock' is low relative to 'totalQuantitySold', suggest a reasonable quantity to reorder to maintain adequate stock based on its sales performance and a buffer. If 'totalQuantitySold' is 0, and 'currentStock' is low, suggest a small reorder quantity (e.g., 5-10 units) to test potential demand.
    - Provide a concise 'reason' for each suggestion.
2.  **Best-Selling Items**: Identify the top products based on their 'totalQuantitySold'. Order this list by 'totalQuantitySold' in descending order. Include only products that have 'totalQuantitySold' greater than 0.

Ensure your output strictly adheres to the JSON schema provided.
`,
});

const optimizedInventorySuggestionsFlow = ai.defineFlow(
  {
    name: 'optimizedInventorySuggestionsFlow',
    inputSchema: OptimizedInventorySuggestionsInputSchema,
    outputSchema: OptimizedInventorySuggestionsOutputSchema,
  },
  async (input) => {
    // Aggregate sales data per product
    const productSalesMap = new Map<number, { totalQuantitySold: number; totalRevenue: number }>();

    input.sales.forEach(sale => {
      sale.items.forEach(item => {
        const currentSales = productSalesMap.get(item.id) || { totalQuantitySold: 0, totalRevenue: 0 };
        currentSales.totalQuantitySold += item.cantidad;
        currentSales.totalRevenue += item.cantidad * item.precio;
        productSalesMap.set(item.id, currentSales);
      });
    });

    // Combine product data with aggregated sales data
    const productsWithSalesData = input.products.map(product => {
      const salesData = productSalesMap.get(product.id) || { totalQuantitySold: 0, totalRevenue: 0 };
      return {
        id: product.id,
        nombre: product.nombre,
        categoria: product.categoria,
        stock: product.stock,
        costo: product.costo,
        precio: product.precio,
        unidad: product.unidad,
        totalQuantitySold: salesData.totalQuantitySold,
        totalRevenue: salesData.totalRevenue,
      };
    });

    // Call the prompt with stringified data to keep the template logic-less
    const { output } = await inventoryPrompt({ 
      productsWithSalesJson: JSON.stringify(productsWithSalesData, null, 2) 
    });
    return output!;
  }
);

/**
 * Generates optimal reorder quantities for products and identifies best-selling items
 * based on historical sales data and current inventory levels.
 *
 * @param input - Contains lists of current products and historical sales records.
 * @returns An object with reorder suggestions and a list of best-selling items.
 */
export async function optimizedInventorySuggestions(
  input: OptimizedInventorySuggestionsInput
): Promise<OptimizedInventorySuggestionsOutput> {
  return optimizedInventorySuggestionsFlow(input);
}
